apiVersion: apps/v1
kind: Deployment
metadata:
  name: nps-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nps
        image: arnabdeysarkar/nps:latest
---
apiVersion: v1
kind: Service
metadata:
  name: nps-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 8086
    targetPort: 8086
    nodePort: 31000